services:
  gateway:
    build:
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    container_name: reward-system-gateway
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AUTH_HOST=auth
      - AUTH_PORT=3001
      - EVENT_HOST=event
      - EVENT_PORT=3002
      - JWT_SECRET=verysecretkey123!nexon
      - JWT_EXPIRATION=1d
    depends_on:
      - auth
      - event
    networks:
      - reward-network

  auth:
    build:
      context: .
      dockerfile: ./docker/auth/Dockerfile
    container_name: reward-system-auth
    restart: always
    ports:
      - '3001:3001'
      - '3004:3004' # Add HTTP port for auth service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://root:root123@cluster0.77urvaw.mongodb.net/reward-system?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=verysecretkey123!nexon
      - JWT_EXPIRATION=1d
    networks:
      - reward-network

  event:
    build:
      context: .
      dockerfile: ./docker/event/Dockerfile
    container_name: reward-system-event
    restart: always
    ports:
      - '3002:3002'
      - '3003:3003' # Add HTTP port for event service
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb+srv://root:root123@cluster0.77urvaw.mongodb.net/reward-system?retryWrites=true&w=majority&appName=Cluster0
      - INNGEST_DEV=true
      - INNGEST_SIGNING_KEY=dev_inngest_signing_key
    networks:
      - reward-network

networks:
  reward-network:
    driver: bridge
# version: '3.8'

# services:
#   gateway:
#     build:
#       context: .
#       dockerfile: ./docker/gateway/Dockerfile
#     container_name: reward-system-gateway
#     restart: always
#     ports:
#       - '3000:3000'
#     environment:
#       - NODE_ENV=development
#       - PORT=3000
#       - AUTH_HOST=auth
#       - AUTH_PORT=3001
#       - EVENT_HOST=event
#       - EVENT_PORT=3002
#       - JWT_SECRET=verysecretkey123!nexon
#       - JWT_EXPIRATION=1d
#     depends_on:
#       - auth
#       - event
#     networks:
#       - reward-network

#   auth:
#     build:
#       context: .
#       dockerfile: ./docker/auth/Dockerfile
#     container_name: reward-system-auth
#     restart: always
#     ports:
#       - '3001:3001'
#     environment:
#       - NODE_ENV=development
#       - PORT=3001
#       - MONGODB_URI=mongodb+srv://root:root123@cluster0.77urvaw.mongodb.net/reward-system?retryWrites=true&w=majority&appName=Cluster0
#       - JWT_SECRET=verysecretkey123!nexon
#       - JWT_EXPIRATION=1d
#     networks:
#       - reward-network

#   event:
#     build:
#       context: .
#       dockerfile: ./docker/event/Dockerfile
#     container_name: reward-system-event
#     restart: always
#     ports:
#       - '3002:3002'
#     environment:
#       - NODE_ENV=development
#       - PORT=3002
#       - MONGODB_URI=mongodb+srv://root:root123@cluster0.77urvaw.mongodb.net/reward-system?retryWrites=true&w=majority&appName=Cluster0
#       - INNGEST_DEV=true
#       - INNGEST_SIGNING_KEY=dev_inngest_signing_key
#     networks:
#       - reward-network

# networks:
#   reward-network:
#     driver: bridge
